### ISSUE TITLE
letter đ is missing

### ISSUE THREAD

**Issue by NQK** [Omnibus-Type/Manuale#1]
The letter đ is missing in all font of the family, except for Regular.

Oh, it seems so only on Google Font Preview.

**Comment by davelab6** [comment]
@NQK thanks for reporting this! But I could not reproduce this on fonts.google.com : 

<img width="622" alt="screen shot 2018-06-20 at 15 54 37" src="https://user-images.githubusercontent.com/261579/41681316-4186b34c-74a2-11e8-8c6c-1757f8dbba97.png">
