### ISSUE TITLE
Can't install regular and italic variants at the same time on Windows 10

### ISSUE THREAD

**Issue by joaopaulo1511** [Omnibus-Type/Manuale#7]
Although Windows 10, version 20H2, recognizes OpenType Variant Fonts, the Manuale variants for roman and italic forms can't be installed together:  Windows complains that Manuale is already installed and asks if we want to replace it, instead of adding the font.

Other variant fonts don't have this issue (Merriweather Sans, for example).

Could you please fix it?

**Comment by Omnibus-Type** [comment]
Hi @joaopaulo1511 Are you using the fonts from Google Fonts or the published in this repository? just in case I just uploaded an update, make the test and if you continue having problems I would appreciate if you write us to confirm the bug or if everything works correctly.

**Comment by joaopaulo1511** [comment]
I got the fonts here in the repository (Google Fonts is sometimes slow to pick up the latest updates).

I tested your update and now the bug is fixed, thank you very much!

**Comment by joaopaulo1511** [comment]
I got the fonts here in this repository (Google Fonts is sometimes slow to pick up the latest updates).

I tested the new font files and these are the results:

- Windows didn't complain anymore that Manuale is already installed and allows me to install both fonts (I installed the Manuale[wght].ttf first and then ManualeItalic[wght].ttf);
- Opening Settings, Personalization, Fonts, Manuale shows that all variants were installed: ![Settings, Personalization, Fonts, Manuale](https://user-images.githubusercontent.com/5490558/100403536-8bb18900-3035-11eb-91c6-b851bd4aadf3.png)
- Opening Control Panel, Fonts, shows only the Manuale (and its variants' names), but not the Manuale Italic typefaces: 
![Control Panel, Fonts, Manuale](https://user-images.githubusercontent.com/5490558/100403733-10040c00-3036-11eb-9ae0-8558dafcbda1.png)
- Opening the fonts inside the Control Panel has erratic effects.  It shows two Manuale Regular typefaces (see the previous picture), one of them opens the Manuale Regular variants (they all can be previewed), the other opens the Manuale Italic and can't show the other variants:
![neural](https://user-images.githubusercontent.com/5490558/100406417-201eea00-303c-11eb-8805-0f8ce4180aca.gif)
- Opening Notepad, Menu Format, Fonts, Manuale (this opens the default font selection dialog on many Windows programs, it is compatible with typefaces with extended styles besides regular/bold/italic/bold italic) shows only the regular variants and not the italic variants:
![Notepad, Format, Font](https://user-images.githubusercontent.com/5490558/100406486-5a888700-303c-11eb-9bf6-2fc9ca180972.png)
- As an example of how it should have been shown, a screen capture of the Merriweather Sans typefaces:
![Notepad 2](https://user-images.githubusercontent.com/5490558/100406884-5d37ac00-303d-11eb-812d-784f8ea94183.png)
- Opening LibreOffice Writer, Menu Format, Character, Font selection dialog (not compatible with extended families) shows the regular variants' names, but the typeface preview shows the italic variants in other weights:
![LibreOffice](https://user-images.githubusercontent.com/5490558/100406690-e39fbe00-303c-11eb-9487-ac45d968e105.png)

After reviewing your changes at commit 25be61ff1c83050a144089271af626fe939f79b1, I saw that you changed the typefaces' names from Manuale and Manuale Italic to "Manuale[wght]" and "ManualeItalic[wght]".  I think the OpenType specification does not allow brackets on the font/typeface internal names, or maybe the problem is the Windows typeface API.

However, I found [a page with examples of how typefaces with extended families should have their name tags defined](https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-id-examples):  The first example does not apply to Manuale, but the second and maybe the third do.

As I am not a typeface designer and don't even know how to open the .glyphs file extension, I can't lend you a hand doing the modification myself.  Please try the naming conventions in that page so the Manuale font will be installed and selectable correctly.

Thanks in advance!

**Comment by Omnibus-Type** [comment]
Hi @joaopaulo1511,  many thanks for expanding the information about the problem, we will review this as soon as possible. The name with the brackets is a requirement of Google Fonts to be able to carry out the corresponding audits with Fontbakery. Can you perform the test only from sources published in Google? this in order to detect if the problem moved to that platform. Before reinstalling try uninstall all fonts before and restart the computer, to avoid any cache problems. If the problem continues, do not hesitate to write us again.

**Comment by joaopaulo1511** [comment]
Hi!

After downloading the variable fonts from Google Fonts (https://fonts.google.com/specimen/Manuale?query=manuale), I could install them and preview them, almost all the glitches were corrected, thanks!

However, there still is a very small glitch to applications unaware of the extended font families (as LibreOffice 7):

Manuale Medium shows on those applications as two typefaces, Manuale Medium with the styles Medium Roman (real style) and Medium Italic (simulated style), and Manuale Medium Italic with only the "Medium Italic Italic" (sic) style:

![image](https://user-images.githubusercontent.com/5490558/102840047-45530e00-43d8-11eb-959e-d35b2a5cff34.png)
![image](https://user-images.githubusercontent.com/5490558/102840060-4c7a1c00-43d8-11eb-81bf-961307cfca3f.png)
![image](https://user-images.githubusercontent.com/5490558/102840071-51d76680-43d8-11eb-837c-dc05386d3f4a.png)

It is a bit annoying, as it is not possible to select the real Medium Italic style by pressing the Italic button or choosing a character or paragraph style that changes the font to the Italic style, because it will use the fake italic style, we have to select the Medium Italic style manually.

However, it is now 99% correct!

Will these corrections be published here on GitHub?

**Comment by thlinard** [comment]
Hi @Omnibus-Type

There is several issues in the `name`, `STAT` and `fvar` tables:

1. Several nameID (263-268) are missing in the Italic VF version.
2. The 400 Weight instance in the `STAT` table received the name "Italic" (you couldn't do that in the `STAT` table, the purpose of the table is to separate axes, very different from the `fvar` table): it should received "Regular", elided.
3. Weight named instances should be mapped to 100x weights.

`gftools gen-stat` can help you.
